name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Fix permissions first
            sudo chown -R ubuntu:ubuntu ~/Comapny_Support_Assistent

            cd ~/Comapny_Support_Assistent

            git fetch origin
            git reset --hard origin/main

            docker stop policy-ai || true
            docker rm   policy-ai || true
            docker rmi  policy-ai-app || true

            docker build -t policy-ai-app .

            docker run -d \
              --name policy-ai \
              --restart always \
              -p 8000:8000 \
              policy-ai-app

            sleep 3
            docker ps | grep policy-ai
            echo "Deployed successfully!"